import{randomUUID}from"node:crypto";import{z}from"zod";import{registerAppTool}from"@modelcontextprotocol/ext-apps/server";import type{McpServer}from"@modelcontextprotocol/sdk/server/mcp.js";import{demoOrganization,demoProject}from"../../data/demoProfiles.js";import{DEFAULT_WEIGHTS,type GrantWatch,type MatchWeights,type OrganizationProfile,type ProjectProfile}from"../../domain/types.js";import{grantRepository}from"../../repositories/grantRepository.js";import{inferRequestedResultCount,MAX_SEARCH_RESULTS,rescoreGrants,searchGrants}from"../../services/grantSearchService.js";import{emailService}from"../../services/emailService.js";
const weights=z.object({missionAlignment:z.number(),applicantEligibility:z.number(),geographicFit:z.number(),programSizeFit:z.number(),historicalSimilarity:z.number(),deadlineFeasibility:z.number()});
const geography=z.object({country:z.string().optional(),states:z.array(z.string()).optional(),nationwide:z.boolean().optional(),description:z.string().optional()});
const organization=z.object({id:z.string().optional(),name:z.string().optional(),organizationType:z.string().optional(),taxStatus:z.string().optional(),headquarters:z.object({city:z.string().optional(),state:z.string().optional(),country:z.string().optional()}).optional(),serviceAreas:z.array(geography).optional(),missionTopics:z.array(z.string()).optional(),populationsServed:z.array(z.string()).optional(),annualBudget:z.number().optional(),priorAnnualRevenue:z.number().optional(),canProvideCostShare:z.boolean().optional(),applicationCapacity:z.enum(["low","medium","high"]).optional()});
const project=z.object({id:z.string().optional(),title:z.string().optional(),summary:z.string().optional(),topics:z.array(z.string()).optional(),targetPopulations:z.array(z.string()).optional(),geographicAreas:z.array(geography).optional(),estimatedBudget:z.number().optional(),desiredStartDate:z.string().optional(),durationMonths:z.number().optional()});
export const searchGrantsSchema=z.object({organization:organization.optional().describe("Known nonprofit profile. Supply only fields supported by the conversation."),project:project.optional().describe("Known project profile. Supply only fields supported by the conversation."),query:z.string().optional(),sources:z.array(z.enum(["grants-gov","irs-990pf"])).optional().describe("Low-level provider filter. Prefer resultTypes when the user specifies current, forecasted, or historical results."),resultTypes:z.array(z.enum(["current-federal","forecasted-federal","historical-private-prospect"])).min(1).optional().describe("Exact record types to return. Use current-federal for currently open Grants.gov opportunities, forecasted-federal for upcoming federal opportunities, and historical-private-prospect for IRS 990-PF giving evidence. Omit historical-private-prospect when the user does not want historical results."),filters:z.object({deadlineAfter:z.string().optional(),deadlineBefore:z.string().optional(),minimumAward:z.number().optional(),maximumAward:z.number().optional(),excludeCostShare:z.boolean().optional(),onlyOpen:z.boolean().describe("Restrict federal opportunities to open status. This does not select record types; use resultTypes for that.").optional(),minimumScore:z.number().optional()}).optional(),weights:weights.optional(),requestedResultCount:z.number().int().optional().describe(`Number of ranked grants requested across all pages. The supported range is 1–${MAX_SEARCH_RESULTS}. Never silently reduce a larger request; return GrantPilot's limit message instead.`),limit:z.number().int().optional().describe("Deprecated alias for requestedResultCount."),refreshData:z.boolean().describe("When true, bypass the normalized result cache and attempt targeted Grants.gov API verification for up to three selected federal results. It never scans raw XML.").default(false)});
export const REQUIRED_TOOLS=["search_grants","load_more_grants","get_grant_details","rescore_grants","compare_grants","create_grant_watch","list_grant_watches","delete_grant_watch","get_project_ideas"] as const;
const mergeOrganization=(value?:z.infer<typeof organization>):OrganizationProfile=>({...demoOrganization,...value,headquarters:{...demoOrganization.headquarters,...value?.headquarters,country:value?.headquarters?.country??demoOrganization.headquarters.country},serviceAreas:value?.serviceAreas??demoOrganization.serviceAreas,missionTopics:value?.missionTopics??demoOrganization.missionTopics,populationsServed:value?.populationsServed??demoOrganization.populationsServed});
const mergeProject=(value?:z.infer<typeof project>):ProjectProfile=>({...demoProject,...value,geographicAreas:value?.geographicAreas??demoProject.geographicAreas,topics:value?.topics??demoProject.topics,targetPopulations:value?.targetPopulations??demoProject.targetPopulations});
const compactSearchOutput=(output:ReturnType<typeof grantRepository.getSearch>,offset=0)=>{
 const records=output.grants.slice(offset).map(item=>({opportunity:{id:item.opportunity.id,source:item.opportunity.source,recordCategory:item.opportunity.recordCategory,title:item.opportunity.title,funderName:item.opportunity.funderName,summary:item.opportunity.summary.slice(0,300),awardMin:item.opportunity.awardMin,awardMax:item.opportunity.awardMax,deadline:item.opportunity.deadline,requiresCostShare:item.opportunity.requiresCostShare,sourceUrl:item.opportunity.sourceUrl,applicationUrl:item.opportunity.applicationUrl,sourceDisclaimer:item.opportunity.sourceDisclaimer.slice(0,160),lastVerifiedAt:item.opportunity.lastVerifiedAt,requirements:item.opportunity.requirements.slice(0,1).map(requirement=>({text:requirement.text.slice(0,140)}))},score:{overallScore:item.score.overallScore,eligibilityStatus:item.score.eligibilityStatus,components:Object.fromEntries(Object.entries(item.score.components).map(([key,component])=>[key,{score:component.score,weight:component.weight,weightedContribution:component.weightedContribution,confidence:component.confidence,reasons:component.reasons.slice(0,1),missingData:component.missingData.slice(0,1)}])),hardExclusions:item.score.hardExclusions.slice(0,1),warnings:item.score.warnings.slice(0,1)},chart:item.chart}));
 const base={queryId:output.queryId,searchedAt:output.searchedAt,weights:output.weights,warnings:output.warnings,totalResultCount:output.grants.length,offset,append:offset>0};
 const grants:typeof records=[];
 for(const record of records){
  const candidate={...base,resultCount:grants.length+1,sourceCounts:{"grants-gov":0,"irs-990pf":0},grants:[...grants,record]};
  if(Buffer.byteLength(JSON.stringify(candidate))>58*1024)break;
  grants.push(record);
 }
 const sourceCounts={"grants-gov":grants.filter(item=>item.opportunity.source==="grants-gov").length,"irs-990pf":grants.filter(item=>item.opportunity.source==="irs-990pf").length};
 const nextOffset=offset+grants.length;
 return{...base,resultCount:grants.length,sourceCounts,grants,nextOffset,hasMore:nextOffset<output.grants.length};
};
export function registerGrantTools(server:McpServer){
 registerAppTool(server,"search_grants",{title:"Search and rank grants",description:`Search and rank the complete local Grants.gov index plus indexed IRS 990-PF historical giving. MUST be used for grant discovery. Use requestedResultCount when the user asks for a specific number; the supported maximum is ${MAX_SEARCH_RESULTS}. Return only records found by this tool: never supplement results with funders or opportunities from general model knowledge. Grants.gov can represent current opportunities; IRS results are historical private-funder prospects, never confirmed open applications.`,inputSchema:searchGrantsSchema,annotations:{readOnlyHint:true,openWorldHint:true},_meta:{ui:{resourceUri:"ui://grantpilot/opportunity-workbench-v2",visibility:["model"]}}},async args=>{console.log("[mcp] tools/call search_grants");const requested=args.requestedResultCount??args.limit??inferRequestedResultCount(args.query)??80;if(requested<1||requested>MAX_SEARCH_RESULTS)return{isError:true,content:[{type:"text",text:`GrantPilot can return between 1 and ${MAX_SEARCH_RESULTS} ranked grants per search. You requested ${requested}. Please request ${MAX_SEARCH_RESULTS} or fewer, or narrow the grant type, topic, geography, award range, or deadline.`}],structuredContent:{error:{code:"RESULT_LIMIT_EXCEEDED",requestedResultCount:requested,minimumResultCount:1,maximumResultCount:MAX_SEARCH_RESULTS}}};const{requestedResultCount:_requested,limit:_legacyLimit,...searchArgs}=args;const output=await searchGrants({...searchArgs,limit:requested,organization:mergeOrganization(args.organization),project:mergeProject(args.project)});const compact=compactSearchOutput(output),top=compact.grants.slice(0,5).map((item,index)=>`${index+1}. ${item.opportunity.title} (${item.opportunity.source}, ${item.score.overallScore}/100)`).join("\n");return{content:[{type:"text",text:`GrantPilot matched ${output.resultCount} of the ${requested} requested records and returned the first ${compact.resultCount} in this payload: ${compact.sourceCounts["grants-gov"]} current/forecasted federal opportunities and ${compact.sourceCounts["irs-990pf"]} historical private-foundation prospects. ${compact.hasMore?"Use load_more_grants for the next page.":"All matched records are loaded."}\n${top||"No sufficiently aligned records passed the filters."}\nUse only the records in this tool result. Do not add or recommend any outside funder or opportunity from general knowledge. IRS 990-PF records are prospect evidence only, not open grants. Verify eligibility, status, deadline, and application details at each original source.`}],structuredContent:compact}});
 server.registerTool("load_more_grants",{description:"Load the next payload-sized page from a cached GrantPilot search without rerunning provider searches. The widget should append and deduplicate these records by grant ID.",inputSchema:z.object({queryId:z.string(),offset:z.number().int().min(0).optional().describe("Use nextOffset from the previous search or load-more result.")}),annotations:{readOnlyHint:true},_meta:{ui:{visibility:["app","model"]}}},async({queryId,offset})=>{console.log("[mcp] tools/call load_more_grants");const search=grantRepository.getSearch(queryId),page=compactSearchOutput(search,offset??0);return{content:[{type:"text",text:`Loaded ${page.resultCount} additional GrantPilot records (${page.nextOffset} of ${page.totalResultCount}). ${page.hasMore?"More cached results remain.":"All cached results are now loaded."}`}],structuredContent:page}});
 server.registerTool("get_grant_details",{description:"Return the normalized opportunity, complete score evidence, requirements, historical context, missing information, warnings, and original source links.",inputSchema:z.object({grantId:z.string()}),annotations:{readOnlyHint:true},_meta:{ui:{visibility:["app","model"]}}},async({grantId})=>{console.log("[mcp] tools/call get_grant_details");const grant=grantRepository.getGrant(grantId);return{content:[{type:"text",text:`Loaded details for ${grant.opportunity.title}.`}],structuredContent:grant}});
 server.registerTool("rescore_grants",{description:"Recalculate cached grant results with new priorities without repeating external API searches. Weights must total 1.",inputSchema:z.object({queryId:z.string(),grantIds:z.array(z.string()),weights}),_meta:{ui:{visibility:["app","model"]}}},async({queryId,grantIds,weights})=>{console.log("[mcp] tools/call rescore_grants");const output=rescoreGrants(queryId,grantIds,weights as MatchWeights);return{content:[{type:"text",text:`Rescored ${output.resultCount} cached grants without repeating provider searches.`}],structuredContent:compactSearchOutput(output)}});
 server.registerTool("compare_grants",{description:"Return a deterministic comparison matrix for two or three grants.",inputSchema:z.object({grantIds:z.array(z.string()).min(2).max(3)}),annotations:{readOnlyHint:true},_meta:{ui:{visibility:["app","model"]}}},async({grantIds})=>{console.log("[mcp] tools/call compare_grants");const grants=grantIds.map(id=>grantRepository.getGrant(id)).map(g=>({id:g.opportunity.id,title:g.opportunity.title,source:g.opportunity.source,overallScore:g.score.overallScore,confidence:Math.round(Object.values(g.score.components).reduce((s,c)=>s+c.confidence,0)/6),eligibilityStatus:g.score.eligibilityStatus,awardRange:`$${(g.opportunity.awardMin??0).toLocaleString()}–$${(g.opportunity.awardMax??0).toLocaleString()}`,deadline:g.opportunity.deadline,daysRemaining:g.chart.daysRemaining,requiresCostShare:g.opportunity.requiresCostShare,applicationEffort:g.chart.applicationEffort,strengths:Object.values(g.score.components).filter(c=>c.score>=80).flatMap(c=>c.reasons).slice(0,3),concerns:[...g.score.warnings,...g.score.hardExclusions],missingData:Object.values(g.score.components).flatMap(c=>c.missingData)}));return{content:[{type:"text",text:`Compared ${grants.length} grants.`}],structuredContent:{grants}}});
 server.registerTool("create_grant_watch",{description:"Create a persistent grant-search watch and send its confirmation through Azure Communication Services Email when configured.",inputSchema:z.object({queryId:z.string(),email:z.string().email(),minimumScore:z.number().min(0).max(100).default(80),notificationTypes:z.array(z.enum(["new-match","deadline-change","opportunity-amended","opportunity-closing","score-increased"])).default(["new-match"]),selectedGrantId:z.string().optional()}),_meta:{ui:{visibility:["app","model"]}}},async input=>{console.log("[mcp] tools/call create_grant_watch");grantRepository.getSearch(input.queryId);const watch:GrantWatch={id:`watch-${randomUUID().slice(0,8)}`,queryId:input.queryId,email:input.email,minimumScore:input.minimumScore,notificationTypes:input.notificationTypes,status:"active",createdAt:new Date().toISOString(),nextCheckAt:new Date(Date.now()+86400000).toISOString(),selectedGrantId:input.selectedGrantId};await grantRepository.saveWatch(watch);const subject=`GrantPilot watch active: ${watch.minimumScore}%+ matches`,delivery=await emailService.send({to:input.email,subject,plainText:`Your GrantPilot watch ${watch.id} is active. Requirements must be verified at the original source.`,html:`<h1>GrantPilot watch active</h1><p>Monitoring for opportunities scoring at least <strong>${watch.minimumScore}%</strong>.</p><p>Verify requirements at the original source.</p>`});return{content:[{type:"text",text:`Watch created. Azure Communication Services Email status: ${delivery.status}.`}],structuredContent:{...watch,emailPreview:{demo:delivery.status==="preview-only",subject,deliveryStatus:delivery.status,provider:delivery.provider}}}});
 server.registerTool("list_grant_watches",{description:"List active GrantPilot watches.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>({content:[{type:"text",text:`${grantRepository.listWatches().length} active watches.`}],structuredContent:{watches:grantRepository.listWatches()}}));
 server.registerTool("delete_grant_watch",{description:"Delete a GrantPilot watch.",inputSchema:z.object({watchId:z.string()}),annotations:{destructiveHint:true}},async({watchId})=>({content:[{type:"text",text:await grantRepository.deleteWatch(watchId)?"Watch deleted.":"Watch was not found."}],structuredContent:{watchId,deleted:!grantRepository.listWatches().some(w=>w.id===watchId)}}));
 server.registerTool("get_project_ideas",{description:"Return structured opportunity evidence that Copilot can use to suggest grounded project concepts. This tool does not call another LLM.",inputSchema:z.object({organization:z.any().optional(),grantIds:z.array(z.string()).min(1)}),annotations:{readOnlyHint:true}},async({grantIds})=>{const grants=grantIds.map(id=>grantRepository.getGrant(id).opportunity),amounts=grants.flatMap(g=>[g.awardMin,g.awardMax]).filter((x):x is number=>x!==undefined);return{content:[{type:"text",text:"Project-idea evidence prepared. Copilot should ground suggestions in these supported themes."}],structuredContent:{commonThemes:[...new Set(grants.flatMap(g=>g.missionTopics))].slice(0,8),commonlyFundedPopulations:[...new Set(grants.flatMap(g=>g.populationsServed))].slice(0,6),commonProjectModels:["employer-partnered training","credential pathway","community learning lab","digital navigation"],typicalAwardRanges:{min:Math.min(...amounts),max:Math.max(...amounts),median:amounts.sort((a,b)=>a-b)[Math.floor(amounts.length/2)]},relevantOpportunityExcerpts:grants.map(g=>({grantId:g.id,title:g.title,supportedActivities:g.missionTopics}))}}});
}
