export type GrantSource="grants-gov"|"irs-990pf";
export type GrantRecordCategory="current-federal-opportunity"|"forecasted-federal-opportunity"|"private-funder-prospect";
export type GeographicEligibility={country?:string;states?:string[];nationwide?:boolean;description?:string};
export type GrantRequirement={id:string;category:"applicant"|"geography"|"financial"|"partnership"|"registration"|"program"|"document"|"other";text:string;required:boolean;machineEvaluable:boolean};
export type GrantOpportunity={id:string;source:GrantSource;sourceId:string;recordCategory:GrantRecordCategory;title:string;funderName:string;funderType:"federal"|"foundation"|"corporate"|"other";summary:string;description?:string;missionTopics:string[];populationsServed:string[];eligibleApplicantTypes:string[];eligibleLocations:GeographicEligibility[];awardMin?:number;awardMax?:number;expectedAwardCount?:number;requiresCostShare?:boolean;costSharePercent?:number;postedDate?:string;deadline?:string;lastUpdated?:string;lastVerifiedAt?:string;fundingOpportunityNumber?:string;assistanceListingNumbers?:string[];opportunityStatus:"open"|"forecasted"|"closed"|"archived"|"unknown";applicationUrl?:string;sourceUrl:string;sourceDisclaimer:string;requirements:GrantRequirement[];rawSourceReference?:string};
export type OrganizationProfile={id:string;name:string;organizationType:string;taxStatus?:string;headquarters:{city?:string;state?:string;country:string};serviceAreas:GeographicEligibility[];missionTopics:string[];populationsServed:string[];annualBudget?:number;priorAnnualRevenue?:number;canProvideCostShare?:boolean;applicationCapacity?:"low"|"medium"|"high";registrations?:{samGov?:"active"|"inactive"|"unknown";grantsGov?:"active"|"inactive"|"unknown"}};
export type ProjectProfile={id:string;title:string;summary:string;topics:string[];targetPopulations:string[];geographicAreas:GeographicEligibility[];estimatedBudget?:number;desiredStartDate?:string;durationMonths?:number};
export type MatchWeights={missionAlignment:number;applicantEligibility:number;geographicFit:number;programSizeFit:number;historicalSimilarity:number;deadlineFeasibility:number};
export type ScoreEvidence={source:"opportunity"|"organization"|"project"|"historical-award";field:string;value:string|number|boolean;sourceUrl?:string};
export type ScoreComponent={score:number;weight:number;weightedContribution:number;confidence:number;reasons:string[];evidence:ScoreEvidence[];missingData:string[]};
export type GrantScore={grantId:string;overallScore:number;components:{missionAlignment:ScoreComponent;applicantEligibility:ScoreComponent;geographicFit:ScoreComponent;programSizeFit:ScoreComponent;historicalSimilarity:ScoreComponent;deadlineFeasibility:ScoreComponent};eligibilityStatus:"confirmed"|"likely"|"possible"|"needs-verification"|"likely-ineligible";hardExclusions:string[];warnings:string[];scoredAt:string};
export type HistoricalEvidence={score:number;confidence:number;reasons:string[];awardCount:number;medianAward?:number;washingtonAwards?:number;source:"irs-990pf"|"usaspending"|"unavailable"};
export type GrantResult={opportunity:GrantOpportunity;score:GrantScore;chart:{applicationEffort:number;matchScore:number;awardAmount?:number;daysRemaining?:number}};
export type SearchOutput={queryId:string;searchedAt:string;resultCount:number;sourceCounts:Record<GrantSource,number>;weights:MatchWeights;grants:GrantResult[];warnings:string[];organization:OrganizationProfile;project:ProjectProfile;awardRange?:{minimumAward?:number;maximumAward?:number}};
export type GrantWatchMatchQuality="worth-reviewing"|"strong"|"top-only";
export type GrantWatchFrequency="as-detected"|"daily"|"weekly";
export type GrantWatchScope="search"|"selected-grant";
export type GrantWatchNotificationType="new-match"|"deadline-change"|"opportunity-amended"|"opportunity-closing"|"score-increased";
export type GrantWatch={
 id:string;
 queryId:string;
 email:string;
 matchQuality:GrantWatchMatchQuality;
 minimumScore:number;
 frequency:GrantWatchFrequency;
 scope:GrantWatchScope;
 deadlineLeadDays:number;
 notificationTypes:GrantWatchNotificationType[];
 status:"active"|"paused";
 createdAt:string;
 nextCheckAt:string;
 copilotReturnUrl?:string;
 selectedGrantId?:string;
 lastNotifiedGrantIds?:string[];
 lastNotifiedEventKeys?:string[];
};
export const DEFAULT_WEIGHTS:MatchWeights={missionAlignment:.30,applicantEligibility:.20,geographicFit:.15,programSizeFit:.15,historicalSimilarity:.10,deadlineFeasibility:.10};
