import{describe,expect,it}from"vitest";import{demoOrganization,demoProject}from"../src/data/demoProfiles.js";import{DEFAULT_WEIGHTS}from"../src/domain/types.js";import{buildRetrievalQueries,inferAwardRange,inferRequestedResultCount,inferResultTypes,rescoreGrants,searchGrants}from"../src/services/grantSearchService.js";
const exactPrompt="Find grants for a Washington nonprofit teaching practical AI skills to low-income adults. We need between $100,000 and $500,000.";
describe("multi-source search",()=>{
 it("combines current opportunities and historical funder prospects",async()=>{const result=await searchGrants({organization:demoOrganization,project:demoProject,limit:20});expect(result.grants.length).toBeGreaterThanOrEqual(10);expect(result.sourceCounts["irs-990pf"]).toBeGreaterThan(0);expect(result.sourceCounts["grants-gov"]).toBeGreaterThan(0);expect(result.grants[0].score.components.missionAlignment.evidence.length).toBeGreaterThan(0);expect(result.grants.filter(item=>item.opportunity.source==="irs-990pf").every(item=>item.opportunity.opportunityStatus==="unknown")).toBe(true)});
 it("expands the demo prompt and preserves only relevant IRS prospects when onlyOpen is requested",async()=>{expect(inferAwardRange(exactPrompt)).toEqual({minimumAward:100000,maximumAward:500000});const queries=buildRetrievalQueries({query:exactPrompt,organization:demoOrganization,project:demoProject});expect(queries).toContain("artificial intelligence");expect(queries).toContain("workforce development");expect(queries).toContain("low income adults");const result=await searchGrants({query:exactPrompt,organization:demoOrganization,project:demoProject,filters:{onlyOpen:true},limit:20,refreshData:true});expect(result.resultCount).toBeGreaterThanOrEqual(3);expect(result.sourceCounts["irs-990pf"]).toBeGreaterThanOrEqual(1);expect(result.grants.every(item=>item.score.components.missionAlignment.score>=45)).toBe(true);expect(result.grants.every(item=>(item.opportunity.awardMax??0)>=100000&&(item.opportunity.awardMin??Number.POSITIVE_INFINITY)<=500000)).toBe(true);expect(result.grants.filter(item=>item.opportunity.source==="grants-gov").every(item=>item.score.eligibilityStatus!=="likely-ineligible")).toBe(true);expect(new Set(result.grants.map(item=>item.chart.applicationEffort)).size).toBeGreaterThanOrEqual(3)});
 it("honors explicit and inferred result types",async()=>{expect(inferResultTypes("Only show current open grants; no historical prospects.")).toEqual(["current-federal"]);expect(inferResultTypes("Show only IRS historical foundation prospects.")).toEqual(["historical-private-prospect"]);const current=await searchGrants({query:`${exactPrompt} Only show current open grants; no historical prospects.`,organization:demoOrganization,project:demoProject,resultTypes:["current-federal"],limit:20});expect(current.grants.length).toBeGreaterThan(0);expect(current.grants.every(item=>item.opportunity.recordCategory==="current-federal-opportunity")).toBe(true);expect(current.sourceCounts["irs-990pf"]).toBe(0);const historical=await searchGrants({query:`${exactPrompt} Show only historical foundation prospects.`,organization:demoOrganization,project:demoProject,resultTypes:["historical-private-prospect"],limit:20});expect(historical.grants.length).toBeGreaterThan(0);expect(historical.grants.every(item=>item.opportunity.recordCategory==="private-funder-prospect")).toBe(true);expect(historical.sourceCounts["grants-gov"]).toBe(0)});
 it("infers requested result counts without confusing award amounts",()=>{expect(inferRequestedResultCount("Show me 40 matching grants for workforce development.")).toBe(40);expect(inferRequestedResultCount("List the top 75 grants.")).toBe(75);expect(inferRequestedResultCount(exactPrompt)).toBeUndefined()});
 it("rescores cached grants without a provider search",async()=>{const result=await searchGrants({organization:demoOrganization,project:demoProject,limit:10});const next=rescoreGrants(result.queryId,result.grants.map(x=>x.opportunity.id),{...DEFAULT_WEIGHTS,missionAlignment:.2,applicantEligibility:.3});expect(next.weights.applicantEligibility).toBe(.3);expect(next.grants).toHaveLength(result.grants.length)});
});
