import{useEffect,useMemo,useState}from"react";import{callTool,connectBridge,followUp,openLink,setBridgeListeners}from"./mcpBridge";import type{GrantResult,SearchOutput,Weights}from"./types";
const labels:Record<keyof Weights,string>={missionAlignment:"Mission",applicantEligibility:"Eligibility",geographicFit:"Geography",programSizeFit:"Program size",historicalSimilarity:"History",deadlineFeasibility:"Deadline"};
const money=(n?:number)=>n===undefined?"Not stated":n>=1e6?`$${(n/1e6).toFixed(1)}M`:`$${Math.round(n/1000)}K`;
const status=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,x=>x.toUpperCase());
export default function App(){const[data,setData]=useState<SearchOutput|null>(null),[selected,setSelected]=useState(""),[compare,setCompare]=useState<string[]>([]),[tab,setTab]=useState<"opportunities"|"compare"|"scores"|"watch">("opportunities"),[notice,setNotice]=useState(""),[email,setEmail]=useState("grants@example.org");
 useEffect(()=>{setBridgeListeners(next=>{setData(next);setSelected(value=>value||next.grants[0]?.opportunity.id)},setNotice);connectBridge()},[]);
 const grant=useMemo(()=>data?.grants.find(x=>x.opportunity.id===selected)??data?.grants[0],[data,selected]);if(!data||!grant)return <main className="loading"><div className="mark">G</div><h2>Opening GrantPilot…</h2><p>Preparing the Grant Opportunity Workbench.</p></main>;
 async function changeWeight(key:keyof Weights,value:number){const old=data!.weights,next={...old,[key]:value/100},others=(Object.keys(old) as (keyof Weights)[]).filter(x=>x!==key),remainder=1-value/100,current=others.reduce((s,x)=>s+old[x],0);others.forEach(x=>next[x]=current?old[x]/current*remainder:remainder/others.length);setNotice("Recalculating cached scores…");try{await callTool("rescore_grants",{queryId:data!.queryId,grantIds:data!.grants.map(x=>x.opportunity.id),weights:next})}catch(e){setNotice(e instanceof Error?e.message:"Unable to rescore")}}
 async function watch(){try{const result=await callTool("create_grant_watch",{queryId:data!.queryId,email,minimumScore:80,notificationTypes:["new-match","opportunity-amended","opportunity-closing"],selectedGrantId:grant!.opportunity.id});setNotice(`Watch ${(result as any).id} created · email ${(result as any).emailPreview?.deliveryStatus}.`)}catch(e){setNotice(e instanceof Error?e.message:"Unable to create watch")}}
 const strong=data.grants.filter(x=>x.score.overallScore>=75).length,urgent=data.grants.filter(x=>(x.chart.daysRemaining??999)<=30).length,review=data.grants.filter(x=>x.score.eligibilityStatus.includes("verification")||x.score.eligibilityStatus.includes("ineligible")).length;
 return <main className="shell"><header><div className="brand"><span className="mark">G</span><div><b>GrantPilot</b><small>Opportunity Workbench</small></div></div><div className="summary"><strong>{data.resultCount} opportunities</strong><span>{strong} strong matches · {urgent} urgent · {review} need review</span></div></header>
 <section className="weights">{(Object.keys(data.weights) as (keyof Weights)[]).map(key=><label key={key}><span>{labels[key]} <b>{Math.round(data.weights[key]*100)}%</b></span><input type="range" min="5" max="50" value={Math.round(data.weights[key]*100)} onChange={e=>changeWeight(key,Number(e.target.value))}/></label>)}</section>
 <section className="work"><div className="plot"><div className="axis y">Match score</div><svg viewBox="0 0 760 430" role="img" aria-label="Grant match score by estimated application effort"><defs><linearGradient id="grid" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#f7f9ff"/><stop offset="1" stopColor="#eef2fb"/></linearGradient></defs><rect x="55" y="20" width="675" height="360" rx="18" fill="url(#grid)"/>{[25,50,75,100].map(v=><g key={v}><line x1="55" x2="730" y1={380-v*3.6} y2={380-v*3.6}/><text x="45" y={385-v*3.6}>{v}</text></g>)}{data.grants.map((item,index)=>{const x=70+item.chart.applicationEffort*6.4,y=380-item.score.overallScore*3.6,r=Math.max(9,Math.min(20,(item.chart.awardAmount??100000)/40000));return <g className={`point ${item.opportunity.source==="irs-990pf"?"private":"federal"} ${item.opportunity.id===grant.opportunity.id?"selected":""}`} key={item.opportunity.id} onClick={()=>setSelected(item.opportunity.id)}><circle cx={x} cy={y} r={r}/><text x={x+r+5} y={y+4}>{index<6?item.opportunity.title.slice(0,24):""}</text><title>{item.opportunity.title} · {item.score.overallScore}% · {money(item.chart.awardAmount)}</title></g>})}<text className="axis-label" x="300" y="420">Estimated application effort →</text></svg><div className="legend"><span><i className="private"/>IRS historical prospect</span><span><i className="federal"/>Current/forecasted federal</span><em>Point size ≈ award amount</em></div></div>
 <aside><div className="source">{grant.opportunity.source==="irs-990pf"?"IRS 990-PF · historical prospect":"Grants.gov · federal"}<span>{status(grant.score.eligibilityStatus)}</span></div><h1>{grant.opportunity.title}</h1><p className="funder">{grant.opportunity.funderName}</p><div className="metrics"><div><strong>{grant.score.overallScore}</strong><small>Match</small></div><div><strong>{Math.round(Object.values(grant.score.components).reduce((s,c)=>s+c.confidence,0)/6)}</strong><small>Confidence</small></div><div><strong>{grant.chart.applicationEffort}</strong><small>Effort</small></div></div><div className="facts"><span>Award <b>{money(grant.opportunity.awardMin)}–{money(grant.opportunity.awardMax)}</b></span><span>{grant.opportunity.source==="irs-990pf"?"Application status":"Deadline"} <b>{grant.opportunity.source==="irs-990pf"?"Unknown · research required":grant.opportunity.deadline??"Verify source"}</b></span></div><p>{grant.opportunity.summary}</p><div className="warning">ⓘ {grant.opportunity.sourceDisclaimer}</div><h3>Why it matches</h3>{Object.entries(grant.score.components).slice(0,4).map(([key,value])=><div className="scoreline" key={key}><span>{labels[key as keyof Weights]} <b>{Math.round(value.score)}</b></span><i><b style={{width:`${value.score}%`}}/></i><small>{value.reasons[0]}</small></div>)}{[...grant.score.warnings,...grant.score.hardExclusions].map(x=><div className="warning" key={x}>△ {x}</div>)}<div className="actions"><button onClick={()=>openLink(grant.opportunity.applicationUrl??grant.opportunity.sourceUrl).catch(e=>setNotice(e.message))}>{grant.opportunity.source==="irs-990pf"?"Open IRS evidence":"Open official source"} ↗</button><button className="primary" onClick={()=>{setTab("watch");watch()}}>Watch</button></div><button className="ask" onClick={()=>followUp(`Explain the largest eligibility risks for ${grant.opportunity.title} and cite the returned GrantPilot evidence.`).catch(e=>setNotice(e.message))}>Ask Copilot about this record</button></aside></section>
 <nav>{(["opportunities","compare","scores","watch"]as const).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{status(x)}</button>)}</nav>
 {tab==="opportunities"&&<div className="drawer list">{data.grants.slice(0,10).map(item=><button key={item.opportunity.id} onClick={()=>setSelected(item.opportunity.id)}><b>{item.score.overallScore}</b><span>{item.opportunity.title}<small>{item.opportunity.funderName} · {money(item.opportunity.awardMax)}</small></span><input type="checkbox" checked={compare.includes(item.opportunity.id)} onChange={e=>setCompare(v=>e.target.checked?[...v,item.opportunity.id].slice(-3):v.filter(id=>id!==item.opportunity.id))}/></button>)}</div>}
 {tab==="compare"&&<div className="drawer"><h3>Comparison set ({compare.length}/3)</h3><button disabled={compare.length<2} onClick={()=>callTool("compare_grants",{grantIds:compare}).then(()=>setNotice("Comparison matrix sent to GrantPilot.")).catch(e=>setNotice(e.message))}>Compare selected grants</button><p>Select grants using the checkboxes in Opportunities.</p></div>}
 {tab==="scores"&&<div className="drawer"><h3>Transparent scoring</h3><p>30% mission alignment · 20% applicant eligibility · 15% geography · 15% program size · 10% historical similarity · 10% deadline feasibility. Unknown fields lower confidence; they do not become negative evidence.</p></div>}
 {tab==="watch"&&<div className="drawer watch"><h3>Watch opportunities like this</h3><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/><button onClick={watch}>Create 80%+ watch</button><small>Email remains preview-only until an email provider is configured.</small></div>}
 {notice&&<button className="toast" onClick={()=>setNotice("")}>{notice} ×</button>}</main>}
