import type {GrantOpportunity,GrantResult,HistoricalEvidence,MatchWeights,OrganizationProfile,ProjectProfile,ScoreComponent,ScoreEvidence} from "../domain/types.js";
import {DEFAULT_WEIGHTS} from "../domain/types.js";
const synonyms:Record<string,string[]>={
 "workforce development":["workforce training","job training","career readiness","employment training","skills development","economic mobility"],
 "digital inclusion":["digital equity","digital access","technology access","digital navigation"],
 "artificial intelligence":["ai","ai literacy","machine learning","responsible ai"],
 "adult education":["adult learning","community learning"]
};
const words=(value:string)=>value.toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(x=>x.length>2&&!["and","the","for","with","from"].includes(x));
const expand=(terms:string[])=>new Set(terms.flatMap(term=>[term,...(synonyms[term.toLowerCase()]??[])]).flatMap(words));
const overlap=(a:string[],b:string[])=>{const left=expand(a),right=expand(b);if(!left.size||!right.size)return 50;return Math.round(100*[...left].filter(x=>right.has(x)).length/Math.min(left.size,right.size))};
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
const component=(score:number,weight:number,confidence:number,reasons:string[],evidence:ScoreEvidence[],missingData:string[]):ScoreComponent=>({score:clamp(score),weight,weightedContribution:clamp(score)*weight,confidence,reasons,evidence,missingData});
export function validateWeights(weights:MatchWeights){const sum=Object.values(weights).reduce((a,b)=>a+b,0);if(Math.abs(sum-1)>.001)throw new Error(`Scoring weights must total 1.0; received ${sum.toFixed(3)}.`)}
export function daysUntil(deadline?:string){return deadline?Math.ceil((Date.parse(deadline)-Date.now())/86400000):undefined}
export function applicationEffort(grant:GrantOpportunity,org:OrganizationProfile){let value=20;if(grant.requiresCostShare)value+=15;if(grant.requirements.some(r=>r.category==="partnership"))value+=15;if(grant.requirements.some(r=>r.category==="registration")&&org.registrations?.samGov!=="active")value+=10;if(grant.requirements.some(r=>r.text.toLowerCase().includes("two-stage")))value+=10;value+=Math.min(20,grant.requirements.filter(r=>r.category==="program").length*5);value+=Math.min(15,grant.requirements.filter(r=>r.category==="document").length*3);if((daysUntil(grant.deadline)??1000)<30)value+=10;return clamp(value)}
const deadlineScore=(days:number|undefined,capacity= "medium")=>{if(days===undefined)return 60;if(days<=0)return 0;const table=capacity==="low"?[[90,100],[61,85],[31,55],[15,20],[1,5]]:capacity==="high"?[[90,100],[61,100],[31,95],[15,80],[1,50]]:[[90,100],[61,95],[31,80],[15,50],[1,20]];return table.find(([minimum])=>days>=minimum)?.[1]??0};
export function scoreGrant(grant:GrantOpportunity,org:OrganizationProfile,project:ProjectProfile,historical:HistoricalEvidence,weights:MatchWeights=DEFAULT_WEIGHTS):GrantResult{
 validateWeights(weights);const privateProspect=grant.recordCategory==="private-funder-prospect";const evidence=(source:ScoreEvidence["source"],field:string,value:ScoreEvidence["value"]):ScoreEvidence=>({source,field,value,sourceUrl:source==="opportunity"?grant.sourceUrl:undefined});
 const topic=overlap(project.topics,grant.missionTopics),mission=overlap(org.missionTopics,grant.missionTopics),population=overlap(project.targetPopulations,grant.populationsServed),text=overlap([...project.topics,...words(project.summary)],[...grant.missionTopics,...words(grant.summary)]);const missionScore=topic*.45+mission*.25+population*.20+text*.10;
 const applicantText=grant.eligibleApplicantTypes.join(" ").toLowerCase(),orgType=org.organizationType.toLowerCase();const explicitlyExcluded=!privateProspect&&applicantText.length>0&&!applicantText.includes(orgType)&&!applicantText.includes("501")&&!applicantText.includes("all");const applicantScore=privateProspect?50:explicitlyExcluded?0:applicantText.includes(orgType)||applicantText.includes("501")?100:50;
 const projectStates=project.geographicAreas.flatMap(x=>x.states??[]),eligibleStates=grant.eligibleLocations.flatMap(x=>x.states??[]),nationwide=grant.eligibleLocations.some(x=>x.nationwide);const geoScore=nationwide?90:projectStates.some(x=>eligibleStates.includes(x))?100:eligibleStates.length?0:50;
 const budget=project.estimatedBudget,min=grant.awardMin,max=grant.awardMax;let sizeScore=60;if(budget!==undefined&&(min!==undefined||max!==undefined)){if((min===undefined||budget>=min)&&(max===undefined||budget<=max))sizeScore=100;else{const boundary=budget<(min??0)?min!:max!;sizeScore=clamp(100-Math.abs(budget-boundary)/boundary*100)}}
 const days=daysUntil(grant.deadline);let deadline=privateProspect?50:deadlineScore(days,org.applicationCapacity);if(grant.requiresCostShare)deadline-=10;if(grant.requirements.some(r=>r.category==="partnership"))deadline-=10;if(grant.requirements.some(r=>r.category==="registration")&&org.registrations?.samGov!=="active")deadline-=10;
 const components={
  missionAlignment:component(missionScore,weights.missionAlignment,90,[`${Math.round(topic)}% project-topic overlap with the opportunity.`],[evidence("project","topics",project.topics.join(", ")),evidence("opportunity","missionTopics",grant.missionTopics.join(", "))],[]),
  applicantEligibility:component(applicantScore,weights.applicantEligibility,privateProspect?25:grant.eligibleApplicantTypes.length?95:45,[privateProspect?"Historical IRS giving does not establish current applicant eligibility.":explicitlyExcluded?"Applicant type conflicts with the stated eligible categories.":"Nonprofit applicant type is supported or not explicitly excluded."],[evidence("organization","organizationType",org.organizationType),evidence("opportunity","eligibleApplicantTypes",grant.eligibleApplicantTypes.join(", "))],privateProspect?["Current application eligibility is unknown."]:grant.eligibleApplicantTypes.length?[]:["Detailed applicant categories are missing."]),
  geographicFit:component(geoScore,weights.geographicFit,eligibleStates.length||nationwide?95:40,[geoScore>=90?"Washington project geography is supported.":"Geographic eligibility needs review."],[evidence("project","geography",projectStates.join(", ")),evidence("opportunity","eligibleLocations",eligibleStates.join(", ")||"Not specified")],eligibleStates.length||nationwide?[]:["Eligible states were not specified."]),
  programSizeFit:component(sizeScore,weights.programSizeFit,min!==undefined||max!==undefined?90:40,[sizeScore===100?"Project budget falls inside the stated award range.":"Project budget differs from the stated or known range."],[evidence("project","estimatedBudget",budget??"Unknown"),evidence("opportunity","awardRange",`${min??"?"}-${max??"?"}`)],min!==undefined||max!==undefined?[]:["No complete award range was supplied."]),
  historicalSimilarity:component(historical.score,weights.historicalSimilarity,historical.confidence,historical.reasons,[evidence("historical-award","comparableAwards",historical.awardCount)],historical.confidence?[]:["Historical award data was unavailable."]),
  deadlineFeasibility:component(deadline,weights.deadlineFeasibility,privateProspect?15:grant.deadline?95:35,[privateProspect?"IRS history does not establish a current application deadline.":days===undefined?"Deadline was not supplied.":`${days} days remain at ${org.applicationCapacity??"medium"} application capacity.`],[evidence("opportunity","deadline",grant.deadline??"Unknown"),evidence("organization","applicationCapacity",org.applicationCapacity??"medium")],grant.deadline?[]:["Deadline is unknown."])
 };
 const overallScore=Object.values(components).reduce((sum,c)=>sum+c.weightedContribution,0);const hardExclusions=explicitlyExcluded?["The opportunity explicitly limits applicants to a different organization type."]:geoScore===0?["Project geography appears outside the stated eligible area."]:[];
 const confidence=Math.round(Object.values(components).reduce((s,c)=>s+c.confidence,0)/6);const status=privateProspect?"needs-verification":hardExclusions.length?"likely-ineligible":applicantScore===100&&geoScore>=90&&confidence>=85?"confirmed":overallScore>=75?"likely":overallScore>=60?"possible":confidence<60?"needs-verification":"possible";
 const warnings=[...(privateProspect?[grant.sourceDisclaimer]:[]),...(grant.requiresCostShare&&org.canProvideCostShare===false?["Cost share is required, but the organization indicated it cannot provide matching funds."]:[]),...(budget&&org.annualBudget&&budget>org.annualBudget*.5?["Requested award exceeds 50% of annual budget; verify administrative capacity."]:[])];
 return{opportunity:grant,score:{grantId:grant.id,overallScore:Math.round(overallScore),components,eligibilityStatus:status,hardExclusions,warnings,scoredAt:new Date().toISOString()},chart:{applicationEffort:applicationEffort(grant,org),matchScore:Math.round(overallScore),awardAmount:max??min,daysRemaining:days}};
}
